class_name ERR_CODE

enum {
	#SCENE
	NONE = 0,
	SCENE_ERROR = 1,
	SCENEMANAGER_NOT_INITED = SCENE_ERROR,
	SCENE_NOT_EXISTS = SCENE_ERROR,
	SCENE_LOAD_FAILED = SCENE_ERROR,
	
	#LOADING
	LOADING_ERROR = 10,
	LOADING_TARGET_INVALID = LOADING_ERROR,
	LOADING_REQUEST_FAILED = LOADING_ERROR,
	LOADING_THREAD_FAILED = LOADING_ERROR,
	LOADING_TIMEOUT = LOADING_ERROR,
	
	#SESSION
	GAMESESSION_ERROR = 20,
	GAMESESSION_CONFIG_NULL = GAMESESSION_ERROR,
	GAMESESSION_SYSTEM_NULL = GAMESESSION_ERROR,
	GAMESESSION_GALAXY_NULL = GAMESESSION_ERROR,
	
	#CONSTANTS.gd
	SOLVE_C_FROM_RATIO_INVALID_TARGET_RATIO = 100,
	HALO_STATE_FROM_MVIR_FAILED_TO_BRACKET_ROOT = 101,
	LOG_MSUN_MASS_NEGATIVE = 102,
	
	#MAPGENERATOR.gd
	MAP_GENERATION_FAILED = 110,
	FAILED_TO_GENERATE_HALO = MAP_GENERATION_FAILED,
	FAILED_TO_GENERATE_DISK_SIZE = MAP_GENERATION_FAILED,
	FAILED_TO_GENERATE_DISK_THICKNESS = MAP_GENERATION_FAILED,
	FAILED_TO_GENERATE_BULGE_PROFILE = MAP_GENERATION_FAILED,
	FAILED_TO_GENERATE_SFR = MAP_GENERATION_FAILED,
	FAILED_TO_GENERATE_METALLICITY = MAP_GENERATION_FAILED,
	
	
}
