class_name ERR_CODE

enum {
	#SCENE
	NONE = 0,
	SCENEMANAGER_NOT_INITED = 1,
	SCENE_NOT_EXISTS = 2,
	SCENE_LOAD_FAILED = 3,
	
	#LOADING
	LOADING_TARGET_INVALID = 10,
	LOADING_REQUEST_FAILED = 11,
	LOADING_THREAD_FAILED = 12,
	LOADING_TIMEOUT = 13,
	
	#SESSION
	GAMESESSION_CONFIG_NULL = 20,
	GAMESESSION_SYSTEM_NULL = 21,
	GAMESESSION_GALAXY_NULL = 22,
	
	#CONSTANTS.gd
	SOLVE_C_FROM_RATIO_INVALID_TARGET_RATIO = 100,
	HALO_STATE_FROM_MVIR_FAILED_TO_BRACKET_ROOT = 101,
	LOG_MSUN_MASS_NEGATIVE = 102,
	
	#MAPGENERATOR.gd
	FAILED_TO_GENERATE_HALO = 110,
	
	# 네트워크 관련 (1000번대)
	NET_TIMEOUT = 1001,
	NET_AUTH_FAILED = 1002,
	
	# 리소스/데이터 관련 (2000번대)
	DATA_CORRUPTED = 2001,
	RESOURCE_NOT_FOUND = 2002,
	
	# 게임 로직 관련 (3000번대)
	INVENTORY_FULL = 3001,
	ITEM_NOT_ENOUGH = 3002
}
